/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ipsec_msg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ipsec_msg.pb-c.h"
void   nefeli__pb__selector__address__init
                     (Nefeli__Pb__Selector__Address         *message)
{
  static Nefeli__Pb__Selector__Address init_value = NEFELI__PB__SELECTOR__ADDRESS__INIT;
  *message = init_value;
}
void   nefeli__pb__selector__port__range__init
                     (Nefeli__Pb__Selector__Port__Range         *message)
{
  static Nefeli__Pb__Selector__Port__Range init_value = NEFELI__PB__SELECTOR__PORT__RANGE__INIT;
  *message = init_value;
}
void   nefeli__pb__selector__port__init
                     (Nefeli__Pb__Selector__Port         *message)
{
  static Nefeli__Pb__Selector__Port init_value = NEFELI__PB__SELECTOR__PORT__INIT;
  *message = init_value;
}
void   nefeli__pb__selector__protocol__init
                     (Nefeli__Pb__Selector__Protocol         *message)
{
  static Nefeli__Pb__Selector__Protocol init_value = NEFELI__PB__SELECTOR__PROTOCOL__INIT;
  *message = init_value;
}
void   nefeli__pb__selector__init
                     (Nefeli__Pb__Selector         *message)
{
  static Nefeli__Pb__Selector init_value = NEFELI__PB__SELECTOR__INIT;
  *message = init_value;
}
size_t nefeli__pb__selector__get_packed_size
                     (const Nefeli__Pb__Selector *message)
{
  assert(message->base.descriptor == &nefeli__pb__selector__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nefeli__pb__selector__pack
                     (const Nefeli__Pb__Selector *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nefeli__pb__selector__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nefeli__pb__selector__pack_to_buffer
                     (const Nefeli__Pb__Selector *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nefeli__pb__selector__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nefeli__Pb__Selector *
       nefeli__pb__selector__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nefeli__Pb__Selector *)
     protobuf_c_message_unpack (&nefeli__pb__selector__descriptor,
                                allocator, len, data);
}
void   nefeli__pb__selector__free_unpacked
                     (Nefeli__Pb__Selector *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &nefeli__pb__selector__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nefeli__pb__sa__init
                     (Nefeli__Pb__SA         *message)
{
  static Nefeli__Pb__SA init_value = NEFELI__PB__SA__INIT;
  *message = init_value;
}
size_t nefeli__pb__sa__get_packed_size
                     (const Nefeli__Pb__SA *message)
{
  assert(message->base.descriptor == &nefeli__pb__sa__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nefeli__pb__sa__pack
                     (const Nefeli__Pb__SA *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nefeli__pb__sa__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nefeli__pb__sa__pack_to_buffer
                     (const Nefeli__Pb__SA *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nefeli__pb__sa__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nefeli__Pb__SA *
       nefeli__pb__sa__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nefeli__Pb__SA *)
     protobuf_c_message_unpack (&nefeli__pb__sa__descriptor,
                                allocator, len, data);
}
void   nefeli__pb__sa__free_unpacked
                     (Nefeli__Pb__SA *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &nefeli__pb__sa__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nefeli__pb__policy__init
                     (Nefeli__Pb__Policy         *message)
{
  static Nefeli__Pb__Policy init_value = NEFELI__PB__POLICY__INIT;
  *message = init_value;
}
size_t nefeli__pb__policy__get_packed_size
                     (const Nefeli__Pb__Policy *message)
{
  assert(message->base.descriptor == &nefeli__pb__policy__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nefeli__pb__policy__pack
                     (const Nefeli__Pb__Policy *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nefeli__pb__policy__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nefeli__pb__policy__pack_to_buffer
                     (const Nefeli__Pb__Policy *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nefeli__pb__policy__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nefeli__Pb__Policy *
       nefeli__pb__policy__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nefeli__Pb__Policy *)
     protobuf_c_message_unpack (&nefeli__pb__policy__descriptor,
                                allocator, len, data);
}
void   nefeli__pb__policy__free_unpacked
                     (Nefeli__Pb__Policy *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &nefeli__pb__policy__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nefeli__pb__ipsec_config__init
                     (Nefeli__Pb__IPsecConfig         *message)
{
  static Nefeli__Pb__IPsecConfig init_value = NEFELI__PB__IPSEC_CONFIG__INIT;
  *message = init_value;
}
size_t nefeli__pb__ipsec_config__get_packed_size
                     (const Nefeli__Pb__IPsecConfig *message)
{
  assert(message->base.descriptor == &nefeli__pb__ipsec_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nefeli__pb__ipsec_config__pack
                     (const Nefeli__Pb__IPsecConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nefeli__pb__ipsec_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nefeli__pb__ipsec_config__pack_to_buffer
                     (const Nefeli__Pb__IPsecConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nefeli__pb__ipsec_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nefeli__Pb__IPsecConfig *
       nefeli__pb__ipsec_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nefeli__Pb__IPsecConfig *)
     protobuf_c_message_unpack (&nefeli__pb__ipsec_config__descriptor,
                                allocator, len, data);
}
void   nefeli__pb__ipsec_config__free_unpacked
                     (Nefeli__Pb__IPsecConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &nefeli__pb__ipsec_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nefeli__pb__ipsec_saconfig__init
                     (Nefeli__Pb__IPsecSAConfig         *message)
{
  static Nefeli__Pb__IPsecSAConfig init_value = NEFELI__PB__IPSEC_SACONFIG__INIT;
  *message = init_value;
}
size_t nefeli__pb__ipsec_saconfig__get_packed_size
                     (const Nefeli__Pb__IPsecSAConfig *message)
{
  assert(message->base.descriptor == &nefeli__pb__ipsec_saconfig__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nefeli__pb__ipsec_saconfig__pack
                     (const Nefeli__Pb__IPsecSAConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nefeli__pb__ipsec_saconfig__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nefeli__pb__ipsec_saconfig__pack_to_buffer
                     (const Nefeli__Pb__IPsecSAConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nefeli__pb__ipsec_saconfig__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nefeli__Pb__IPsecSAConfig *
       nefeli__pb__ipsec_saconfig__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nefeli__Pb__IPsecSAConfig *)
     protobuf_c_message_unpack (&nefeli__pb__ipsec_saconfig__descriptor,
                                allocator, len, data);
}
void   nefeli__pb__ipsec_saconfig__free_unpacked
                     (Nefeli__Pb__IPsecSAConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &nefeli__pb__ipsec_saconfig__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nefeli__pb__endpoint_config__init
                     (Nefeli__Pb__EndpointConfig         *message)
{
  static Nefeli__Pb__EndpointConfig init_value = NEFELI__PB__ENDPOINT_CONFIG__INIT;
  *message = init_value;
}
size_t nefeli__pb__endpoint_config__get_packed_size
                     (const Nefeli__Pb__EndpointConfig *message)
{
  assert(message->base.descriptor == &nefeli__pb__endpoint_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nefeli__pb__endpoint_config__pack
                     (const Nefeli__Pb__EndpointConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nefeli__pb__endpoint_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nefeli__pb__endpoint_config__pack_to_buffer
                     (const Nefeli__Pb__EndpointConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nefeli__pb__endpoint_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nefeli__Pb__EndpointConfig *
       nefeli__pb__endpoint_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nefeli__Pb__EndpointConfig *)
     protobuf_c_message_unpack (&nefeli__pb__endpoint_config__descriptor,
                                allocator, len, data);
}
void   nefeli__pb__endpoint_config__free_unpacked
                     (Nefeli__Pb__EndpointConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &nefeli__pb__endpoint_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nefeli__pb__ipsec_inbound_arg__init
                     (Nefeli__Pb__IPsecInboundArg         *message)
{
  static Nefeli__Pb__IPsecInboundArg init_value = NEFELI__PB__IPSEC_INBOUND_ARG__INIT;
  *message = init_value;
}
size_t nefeli__pb__ipsec_inbound_arg__get_packed_size
                     (const Nefeli__Pb__IPsecInboundArg *message)
{
  assert(message->base.descriptor == &nefeli__pb__ipsec_inbound_arg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nefeli__pb__ipsec_inbound_arg__pack
                     (const Nefeli__Pb__IPsecInboundArg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nefeli__pb__ipsec_inbound_arg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nefeli__pb__ipsec_inbound_arg__pack_to_buffer
                     (const Nefeli__Pb__IPsecInboundArg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nefeli__pb__ipsec_inbound_arg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nefeli__Pb__IPsecInboundArg *
       nefeli__pb__ipsec_inbound_arg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nefeli__Pb__IPsecInboundArg *)
     protobuf_c_message_unpack (&nefeli__pb__ipsec_inbound_arg__descriptor,
                                allocator, len, data);
}
void   nefeli__pb__ipsec_inbound_arg__free_unpacked
                     (Nefeli__Pb__IPsecInboundArg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &nefeli__pb__ipsec_inbound_arg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nefeli__pb__ipsec_outbound_arg__init
                     (Nefeli__Pb__IPsecOutboundArg         *message)
{
  static Nefeli__Pb__IPsecOutboundArg init_value = NEFELI__PB__IPSEC_OUTBOUND_ARG__INIT;
  *message = init_value;
}
size_t nefeli__pb__ipsec_outbound_arg__get_packed_size
                     (const Nefeli__Pb__IPsecOutboundArg *message)
{
  assert(message->base.descriptor == &nefeli__pb__ipsec_outbound_arg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nefeli__pb__ipsec_outbound_arg__pack
                     (const Nefeli__Pb__IPsecOutboundArg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nefeli__pb__ipsec_outbound_arg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nefeli__pb__ipsec_outbound_arg__pack_to_buffer
                     (const Nefeli__Pb__IPsecOutboundArg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nefeli__pb__ipsec_outbound_arg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nefeli__Pb__IPsecOutboundArg *
       nefeli__pb__ipsec_outbound_arg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nefeli__Pb__IPsecOutboundArg *)
     protobuf_c_message_unpack (&nefeli__pb__ipsec_outbound_arg__descriptor,
                                allocator, len, data);
}
void   nefeli__pb__ipsec_outbound_arg__free_unpacked
                     (Nefeli__Pb__IPsecOutboundArg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &nefeli__pb__ipsec_outbound_arg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nefeli__pb__ipsec_stats__init
                     (Nefeli__Pb__IPsecStats         *message)
{
  static Nefeli__Pb__IPsecStats init_value = NEFELI__PB__IPSEC_STATS__INIT;
  *message = init_value;
}
size_t nefeli__pb__ipsec_stats__get_packed_size
                     (const Nefeli__Pb__IPsecStats *message)
{
  assert(message->base.descriptor == &nefeli__pb__ipsec_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nefeli__pb__ipsec_stats__pack
                     (const Nefeli__Pb__IPsecStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nefeli__pb__ipsec_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nefeli__pb__ipsec_stats__pack_to_buffer
                     (const Nefeli__Pb__IPsecStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nefeli__pb__ipsec_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nefeli__Pb__IPsecStats *
       nefeli__pb__ipsec_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nefeli__Pb__IPsecStats *)
     protobuf_c_message_unpack (&nefeli__pb__ipsec_stats__descriptor,
                                allocator, len, data);
}
void   nefeli__pb__ipsec_stats__free_unpacked
                     (Nefeli__Pb__IPsecStats *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &nefeli__pb__ipsec_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor nefeli__pb__selector__address__field_descriptors[2] =
{
  {
    "any",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Nefeli__Pb__Selector__Address, value_case),
    offsetof(Nefeli__Pb__Selector__Address, any),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "literal",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Nefeli__Pb__Selector__Address, value_case),
    offsetof(Nefeli__Pb__Selector__Address, literal),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nefeli__pb__selector__address__field_indices_by_name[] = {
  0,   /* field[0] = any */
  1,   /* field[1] = literal */
};
static const ProtobufCIntRange nefeli__pb__selector__address__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nefeli__pb__selector__address__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nefeli.pb.Selector.Address",
  "Address",
  "Nefeli__Pb__Selector__Address",
  "nefeli.pb",
  sizeof(Nefeli__Pb__Selector__Address),
  2,
  nefeli__pb__selector__address__field_descriptors,
  nefeli__pb__selector__address__field_indices_by_name,
  1,  nefeli__pb__selector__address__number_ranges,
  (ProtobufCMessageInit) nefeli__pb__selector__address__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nefeli__pb__selector__port__range__field_descriptors[2] =
{
  {
    "start",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Nefeli__Pb__Selector__Port__Range, has_start),
    offsetof(Nefeli__Pb__Selector__Port__Range, start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Nefeli__Pb__Selector__Port__Range, has_end),
    offsetof(Nefeli__Pb__Selector__Port__Range, end),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nefeli__pb__selector__port__range__field_indices_by_name[] = {
  1,   /* field[1] = end */
  0,   /* field[0] = start */
};
static const ProtobufCIntRange nefeli__pb__selector__port__range__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nefeli__pb__selector__port__range__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nefeli.pb.Selector.Port.Range",
  "Range",
  "Nefeli__Pb__Selector__Port__Range",
  "nefeli.pb",
  sizeof(Nefeli__Pb__Selector__Port__Range),
  2,
  nefeli__pb__selector__port__range__field_descriptors,
  nefeli__pb__selector__port__range__field_indices_by_name,
  1,  nefeli__pb__selector__port__range__number_ranges,
  (ProtobufCMessageInit) nefeli__pb__selector__port__range__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nefeli__pb__selector__port__field_descriptors[3] =
{
  {
    "any",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Nefeli__Pb__Selector__Port, value_case),
    offsetof(Nefeli__Pb__Selector__Port, any),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "opaque",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Nefeli__Pb__Selector__Port, value_case),
    offsetof(Nefeli__Pb__Selector__Port, opaque),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "literal",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Nefeli__Pb__Selector__Port, value_case),
    offsetof(Nefeli__Pb__Selector__Port, literal),
    &nefeli__pb__selector__port__range__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nefeli__pb__selector__port__field_indices_by_name[] = {
  0,   /* field[0] = any */
  2,   /* field[2] = literal */
  1,   /* field[1] = opaque */
};
static const ProtobufCIntRange nefeli__pb__selector__port__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor nefeli__pb__selector__port__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nefeli.pb.Selector.Port",
  "Port",
  "Nefeli__Pb__Selector__Port",
  "nefeli.pb",
  sizeof(Nefeli__Pb__Selector__Port),
  3,
  nefeli__pb__selector__port__field_descriptors,
  nefeli__pb__selector__port__field_indices_by_name,
  1,  nefeli__pb__selector__port__number_ranges,
  (ProtobufCMessageInit) nefeli__pb__selector__port__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nefeli__pb__selector__protocol__field_descriptors[2] =
{
  {
    "any",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Nefeli__Pb__Selector__Protocol, value_case),
    offsetof(Nefeli__Pb__Selector__Protocol, any),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "literal",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Nefeli__Pb__Selector__Protocol, value_case),
    offsetof(Nefeli__Pb__Selector__Protocol, literal),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nefeli__pb__selector__protocol__field_indices_by_name[] = {
  0,   /* field[0] = any */
  1,   /* field[1] = literal */
};
static const ProtobufCIntRange nefeli__pb__selector__protocol__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nefeli__pb__selector__protocol__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nefeli.pb.Selector.Protocol",
  "Protocol",
  "Nefeli__Pb__Selector__Protocol",
  "nefeli.pb",
  sizeof(Nefeli__Pb__Selector__Protocol),
  2,
  nefeli__pb__selector__protocol__field_descriptors,
  nefeli__pb__selector__protocol__field_indices_by_name,
  1,  nefeli__pb__selector__protocol__number_ranges,
  (ProtobufCMessageInit) nefeli__pb__selector__protocol__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nefeli__pb__selector__field_descriptors[5] =
{
  {
    "remote_addrs",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nefeli__Pb__Selector, remote_addrs),
    &nefeli__pb__selector__address__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "local_addrs",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nefeli__Pb__Selector, local_addrs),
    &nefeli__pb__selector__address__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proto",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nefeli__Pb__Selector, proto),
    &nefeli__pb__selector__protocol__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remote_ports",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nefeli__Pb__Selector, remote_ports),
    &nefeli__pb__selector__port__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "local_ports",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nefeli__Pb__Selector, local_ports),
    &nefeli__pb__selector__port__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nefeli__pb__selector__field_indices_by_name[] = {
  1,   /* field[1] = local_addrs */
  4,   /* field[4] = local_ports */
  2,   /* field[2] = proto */
  0,   /* field[0] = remote_addrs */
  3,   /* field[3] = remote_ports */
};
static const ProtobufCIntRange nefeli__pb__selector__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor nefeli__pb__selector__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nefeli.pb.Selector",
  "Selector",
  "Nefeli__Pb__Selector",
  "nefeli.pb",
  sizeof(Nefeli__Pb__Selector),
  5,
  nefeli__pb__selector__field_descriptors,
  nefeli__pb__selector__field_indices_by_name,
  1,  nefeli__pb__selector__number_ranges,
  (ProtobufCMessageInit) nefeli__pb__selector__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nefeli__pb__sa__field_descriptors[9] =
{
  {
    "local",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Nefeli__Pb__SA, has_local),
    offsetof(Nefeli__Pb__SA, local),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remote",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Nefeli__Pb__SA, has_remote),
    offsetof(Nefeli__Pb__SA, remote),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spi",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Nefeli__Pb__SA, has_spi),
    offsetof(Nefeli__Pb__SA, spi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tunnel",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Nefeli__Pb__SA, has_tunnel),
    offsetof(Nefeli__Pb__SA, tunnel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "encr_alg",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Nefeli__Pb__SA, has_encr_alg),
    offsetof(Nefeli__Pb__SA, encr_alg),
    &nefeli__pb__encryption_algorithm__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "encr_key",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Nefeli__Pb__SA, has_encr_key),
    offsetof(Nefeli__Pb__SA, encr_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iv",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Nefeli__Pb__SA, has_iv),
    offsetof(Nefeli__Pb__SA, iv),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "selectors",
    14,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Nefeli__Pb__SA, n_selectors),
    offsetof(Nefeli__Pb__SA, selectors),
    &nefeli__pb__selector__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "udp_encap",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Nefeli__Pb__SA, has_udp_encap),
    offsetof(Nefeli__Pb__SA, udp_encap),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nefeli__pb__sa__field_indices_by_name[] = {
  4,   /* field[4] = encr_alg */
  5,   /* field[5] = encr_key */
  6,   /* field[6] = iv */
  0,   /* field[0] = local */
  1,   /* field[1] = remote */
  7,   /* field[7] = selectors */
  2,   /* field[2] = spi */
  3,   /* field[3] = tunnel */
  8,   /* field[8] = udp_encap */
};
static const ProtobufCIntRange nefeli__pb__sa__number_ranges[2 + 1] =
{
  { 4, 0 },
  { 14, 7 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor nefeli__pb__sa__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nefeli.pb.SA",
  "SA",
  "Nefeli__Pb__SA",
  "nefeli.pb",
  sizeof(Nefeli__Pb__SA),
  9,
  nefeli__pb__sa__field_descriptors,
  nefeli__pb__sa__field_indices_by_name,
  2,  nefeli__pb__sa__number_ranges,
  (ProtobufCMessageInit) nefeli__pb__sa__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue nefeli__pb__policy__processing_choice__enum_values_by_number[3] =
{
  { "DISCARD", "NEFELI__PB__POLICY__PROCESSING_CHOICE__DISCARD", 0 },
  { "BYPASS", "NEFELI__PB__POLICY__PROCESSING_CHOICE__BYPASS", 1 },
  { "PROTECT", "NEFELI__PB__POLICY__PROCESSING_CHOICE__PROTECT", 2 },
};
static const ProtobufCIntRange nefeli__pb__policy__processing_choice__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex nefeli__pb__policy__processing_choice__enum_values_by_name[3] =
{
  { "BYPASS", 1 },
  { "DISCARD", 0 },
  { "PROTECT", 2 },
};
const ProtobufCEnumDescriptor nefeli__pb__policy__processing_choice__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "nefeli.pb.Policy.ProcessingChoice",
  "ProcessingChoice",
  "Nefeli__Pb__Policy__ProcessingChoice",
  "nefeli.pb",
  3,
  nefeli__pb__policy__processing_choice__enum_values_by_number,
  3,
  nefeli__pb__policy__processing_choice__enum_values_by_name,
  1,
  nefeli__pb__policy__processing_choice__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor nefeli__pb__policy__field_descriptors[3] =
{
  {
    "selectors",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Nefeli__Pb__Policy, n_selectors),
    offsetof(Nefeli__Pb__Policy, selectors),
    &nefeli__pb__selector__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "processing_choice",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Nefeli__Pb__Policy, has_processing_choice),
    offsetof(Nefeli__Pb__Policy, processing_choice),
    &nefeli__pb__policy__processing_choice__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spis",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Nefeli__Pb__Policy, n_spis),
    offsetof(Nefeli__Pb__Policy, spis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nefeli__pb__policy__field_indices_by_name[] = {
  1,   /* field[1] = processing_choice */
  0,   /* field[0] = selectors */
  2,   /* field[2] = spis */
};
static const ProtobufCIntRange nefeli__pb__policy__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 5, 2 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor nefeli__pb__policy__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nefeli.pb.Policy",
  "Policy",
  "Nefeli__Pb__Policy",
  "nefeli.pb",
  sizeof(Nefeli__Pb__Policy),
  3,
  nefeli__pb__policy__field_descriptors,
  nefeli__pb__policy__field_indices_by_name,
  3,  nefeli__pb__policy__number_ranges,
  (ProtobufCMessageInit) nefeli__pb__policy__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nefeli__pb__ipsec_config__field_descriptors[2] =
{
  {
    "sad",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Nefeli__Pb__IPsecConfig, n_sad),
    offsetof(Nefeli__Pb__IPsecConfig, sad),
    &nefeli__pb__sa__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spd",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Nefeli__Pb__IPsecConfig, n_spd),
    offsetof(Nefeli__Pb__IPsecConfig, spd),
    &nefeli__pb__policy__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nefeli__pb__ipsec_config__field_indices_by_name[] = {
  0,   /* field[0] = sad */
  1,   /* field[1] = spd */
};
static const ProtobufCIntRange nefeli__pb__ipsec_config__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nefeli__pb__ipsec_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nefeli.pb.IPsecConfig",
  "IPsecConfig",
  "Nefeli__Pb__IPsecConfig",
  "nefeli.pb",
  sizeof(Nefeli__Pb__IPsecConfig),
  2,
  nefeli__pb__ipsec_config__field_descriptors,
  nefeli__pb__ipsec_config__field_indices_by_name,
  1,  nefeli__pb__ipsec_config__number_ranges,
  (ProtobufCMessageInit) nefeli__pb__ipsec_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nefeli__pb__ipsec_saconfig__field_descriptors[1] =
{
  {
    "sa",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nefeli__Pb__IPsecSAConfig, sa),
    &nefeli__pb__sa__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nefeli__pb__ipsec_saconfig__field_indices_by_name[] = {
  0,   /* field[0] = sa */
};
static const ProtobufCIntRange nefeli__pb__ipsec_saconfig__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor nefeli__pb__ipsec_saconfig__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nefeli.pb.IPsecSAConfig",
  "IPsecSAConfig",
  "Nefeli__Pb__IPsecSAConfig",
  "nefeli.pb",
  sizeof(Nefeli__Pb__IPsecSAConfig),
  1,
  nefeli__pb__ipsec_saconfig__field_descriptors,
  nefeli__pb__ipsec_saconfig__field_indices_by_name,
  1,  nefeli__pb__ipsec_saconfig__number_ranges,
  (ProtobufCMessageInit) nefeli__pb__ipsec_saconfig__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nefeli__pb__endpoint_config__field_descriptors[2] =
{
  {
    "remote",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Nefeli__Pb__EndpointConfig, has_remote),
    offsetof(Nefeli__Pb__EndpointConfig, remote),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "local",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Nefeli__Pb__EndpointConfig, has_local),
    offsetof(Nefeli__Pb__EndpointConfig, local),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nefeli__pb__endpoint_config__field_indices_by_name[] = {
  1,   /* field[1] = local */
  0,   /* field[0] = remote */
};
static const ProtobufCIntRange nefeli__pb__endpoint_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nefeli__pb__endpoint_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nefeli.pb.EndpointConfig",
  "EndpointConfig",
  "Nefeli__Pb__EndpointConfig",
  "nefeli.pb",
  sizeof(Nefeli__Pb__EndpointConfig),
  2,
  nefeli__pb__endpoint_config__field_descriptors,
  nefeli__pb__endpoint_config__field_indices_by_name,
  1,  nefeli__pb__endpoint_config__number_ranges,
  (ProtobufCMessageInit) nefeli__pb__endpoint_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nefeli__pb__ipsec_inbound_arg__field_descriptors[2] =
{
  {
    "pipeline",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Nefeli__Pb__IPsecInboundArg, pipeline),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eth_frame",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Nefeli__Pb__IPsecInboundArg, has_eth_frame),
    offsetof(Nefeli__Pb__IPsecInboundArg, eth_frame),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nefeli__pb__ipsec_inbound_arg__field_indices_by_name[] = {
  1,   /* field[1] = eth_frame */
  0,   /* field[0] = pipeline */
};
static const ProtobufCIntRange nefeli__pb__ipsec_inbound_arg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nefeli__pb__ipsec_inbound_arg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nefeli.pb.IPsecInboundArg",
  "IPsecInboundArg",
  "Nefeli__Pb__IPsecInboundArg",
  "nefeli.pb",
  sizeof(Nefeli__Pb__IPsecInboundArg),
  2,
  nefeli__pb__ipsec_inbound_arg__field_descriptors,
  nefeli__pb__ipsec_inbound_arg__field_indices_by_name,
  1,  nefeli__pb__ipsec_inbound_arg__number_ranges,
  (ProtobufCMessageInit) nefeli__pb__ipsec_inbound_arg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nefeli__pb__ipsec_outbound_arg__field_descriptors[4] =
{
  {
    "pipeline",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Nefeli__Pb__IPsecOutboundArg, pipeline),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eth_frame",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Nefeli__Pb__IPsecOutboundArg, has_eth_frame),
    offsetof(Nefeli__Pb__IPsecOutboundArg, eth_frame),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remote",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Nefeli__Pb__IPsecOutboundArg, has_remote),
    offsetof(Nefeli__Pb__IPsecOutboundArg, remote),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "local",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Nefeli__Pb__IPsecOutboundArg, has_local),
    offsetof(Nefeli__Pb__IPsecOutboundArg, local),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nefeli__pb__ipsec_outbound_arg__field_indices_by_name[] = {
  1,   /* field[1] = eth_frame */
  3,   /* field[3] = local */
  0,   /* field[0] = pipeline */
  2,   /* field[2] = remote */
};
static const ProtobufCIntRange nefeli__pb__ipsec_outbound_arg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor nefeli__pb__ipsec_outbound_arg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nefeli.pb.IPsecOutboundArg",
  "IPsecOutboundArg",
  "Nefeli__Pb__IPsecOutboundArg",
  "nefeli.pb",
  sizeof(Nefeli__Pb__IPsecOutboundArg),
  4,
  nefeli__pb__ipsec_outbound_arg__field_descriptors,
  nefeli__pb__ipsec_outbound_arg__field_indices_by_name,
  1,  nefeli__pb__ipsec_outbound_arg__number_ranges,
  (ProtobufCMessageInit) nefeli__pb__ipsec_outbound_arg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nefeli__pb__ipsec_stats__field_descriptors[4] =
{
  {
    "invalid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Nefeli__Pb__IPsecStats, has_invalid),
    offsetof(Nefeli__Pb__IPsecStats, invalid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "discard",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Nefeli__Pb__IPsecStats, has_discard),
    offsetof(Nefeli__Pb__IPsecStats, discard),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bypass",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Nefeli__Pb__IPsecStats, has_bypass),
    offsetof(Nefeli__Pb__IPsecStats, bypass),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "protect",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Nefeli__Pb__IPsecStats, has_protect),
    offsetof(Nefeli__Pb__IPsecStats, protect),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nefeli__pb__ipsec_stats__field_indices_by_name[] = {
  2,   /* field[2] = bypass */
  1,   /* field[1] = discard */
  0,   /* field[0] = invalid */
  3,   /* field[3] = protect */
};
static const ProtobufCIntRange nefeli__pb__ipsec_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor nefeli__pb__ipsec_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nefeli.pb.IPsecStats",
  "IPsecStats",
  "Nefeli__Pb__IPsecStats",
  "nefeli.pb",
  sizeof(Nefeli__Pb__IPsecStats),
  4,
  nefeli__pb__ipsec_stats__field_descriptors,
  nefeli__pb__ipsec_stats__field_indices_by_name,
  1,  nefeli__pb__ipsec_stats__number_ranges,
  (ProtobufCMessageInit) nefeli__pb__ipsec_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue nefeli__pb__encryption_algorithm__enum_values_by_number[2] =
{
  { "NULL_ENCR", "NEFELI__PB__ENCRYPTION_ALGORITHM__NULL_ENCR", 0 },
  { "AES_GCM", "NEFELI__PB__ENCRYPTION_ALGORITHM__AES_GCM", 1 },
};
static const ProtobufCIntRange nefeli__pb__encryption_algorithm__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex nefeli__pb__encryption_algorithm__enum_values_by_name[2] =
{
  { "AES_GCM", 1 },
  { "NULL_ENCR", 0 },
};
const ProtobufCEnumDescriptor nefeli__pb__encryption_algorithm__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "nefeli.pb.EncryptionAlgorithm",
  "EncryptionAlgorithm",
  "Nefeli__Pb__EncryptionAlgorithm",
  "nefeli.pb",
  2,
  nefeli__pb__encryption_algorithm__enum_values_by_number,
  2,
  nefeli__pb__encryption_algorithm__enum_values_by_name,
  1,
  nefeli__pb__encryption_algorithm__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
